# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainFrm.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/新前缀/icon/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchlineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.searchlineEdit.setFont(font)
        self.searchlineEdit.setObjectName("searchlineEdit")
        self.horizontalLayout.addWidget(self.searchlineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.searchContentButton = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.searchContentButton.setFont(font)
        self.searchContentButton.setObjectName("searchContentButton")
        self.horizontalLayout.addWidget(self.searchContentButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.resulttreeView = QtWidgets.QTreeView(self.frame)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.resulttreeView.setFont(font)
        self.resulttreeView.setStyleSheet("item{height:205px}")
        self.resulttreeView.setSortingEnabled(True)
        self.resulttreeView.setObjectName("resulttreeView")
        self.verticalLayout_3.addWidget(self.resulttreeView)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contenttextEdit = QtWidgets.QTextEdit(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(20)
        self.contenttextEdit.setFont(font)
        self.contenttextEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.contenttextEdit.setStyleSheet("")
        self.contenttextEdit.setObjectName("contenttextEdit")
        self.verticalLayout_2.addWidget(self.contenttextEdit)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.loadOfflineAction = QtWidgets.QAction(MainWindow)
        self.loadOfflineAction.setObjectName("loadOfflineAction")
        self.updateOnlineaction = QtWidgets.QAction(MainWindow)
        self.updateOnlineaction.setObjectName("updateOnlineaction")
        self.menu.addAction(self.loadOfflineAction)
        self.menu_2.addAction(self.updateOnlineaction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "公文小助手"))
        self.pushButton.setText(_translate("MainWindow", "查询标题"))
        self.searchContentButton.setText(_translate("MainWindow", "查询内容"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "升级"))
        self.loadOfflineAction.setText(_translate("MainWindow", "导入离线数据包"))
        self.updateOnlineaction.setText(_translate("MainWindow", "在线升级报纸"))

